[project]
name = "evalmatch"

[environment]
name = "production"

[build]
command = "npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/health"
healthcheckTimeout = 300