[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
# startCommand removed - using Dockerfile CMD instead
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

# Environment variables
[deploy.variables]
NODE_ENV = "production"
NODE_OPTIONS = "--max-old-space-size=7168 --max-semi-space-size=256"
ENABLE_TELEMETRY = "true"
ENABLE_LOCAL_EMBEDDINGS = "true"
EMBEDDING_MODEL = "Xenova/all-MiniLM-L6-v2"
MAX_CONCURRENT_EMBEDDINGS = "3"
# Railway optimization settings
RAILWAY_HEALTHCHECK_TIMEOUT = "15000"
AI_HEALTH_CHECK_ENABLED = "false"
HEALTH_CHECK_AI_TIMEOUT = "2000"
# Disable Redis for Railway deployment to avoid connection issues
REDIS_ENABLED = "false"
LOG_LEVEL = "info"

# Memory and CPU limits for Railway
[deploy.resources]
memory = 8192  # 8GB RAM - plenty for advanced embeddings and ML models
cpu = 2000     # 2 vCPU for better performance

# Railway-specific optimizations
[deploy.healthCheck]
path = "/api/health/railway"
initialDelaySeconds = 60
periodSeconds = 30
timeoutSeconds = 10
successThreshold = 1
failureThreshold = 3