version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*

  document-search-service:
    build:
      context: ./document-search-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
      - PYTHONPATH=/app
    volumes:
      - ./document-search-service:/app

  ai-chat-service:
    build:
      context: ./ai-chat-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - redis
      - ollama
      - document-search-service
    environment:
      - REDIS_URL=redis://redis:6379
      - OLLAMA_BASE_URL=http://ollama:11434
      - DOCUMENT_SEARCH_URL=http://document-search-service:8001
      - PYTHONPATH=/app
    volumes:
      - ./ai-chat-service:/app

  nginx:
    image: nginx:alpine
    ports:
      - "8000:8000"
    depends_on:
      - ai-chat-service
      - document-search-service
    volumes:
      - ./config/nginx-simple.conf:/etc/nginx/conf.d/default.conf
      - ./ui:/usr/share/nginx/html
    command: nginx -g 'daemon off;'

volumes:
  redis_data:
  ollama_data:
