# Fly.io configuration for Unified AI Platform
# Combined ideal-octo-goggles + ubiquitous-octo-invention integration

app = "unified-ai-platform"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile.light"

[env]
  PORT = "8000"
  PYTHONPATH = "/app"
  EMBEDDING_DIM = "384"
  USE_GPU = "false"
  INDEX_PATH = "/app/indexes"
  UPLOAD_PATH = "/app/data/uploads"
  ENVIRONMENT = "production"
  PLATFORM_MODE = "unified"

[[services]]
  internal_port = 8000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [[services.http_checks]]
    interval = "10s"
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = false

[experimental]
  auto_rollback = true

[[vm]]
  cpu_kind = "shared"
  cpus = 2
  memory_mb = 2048